language: python

os: linux

env:
  global:
    # DOCKER_USERNAME
    - secure: qJZy2rynJGrHj5++Yf8/LV6SnkLYtN7OD+y9WTFye7cRsKHNRA9c4Apa0Hs2MJ9WVQIE2Y2ITKZ6nGdL0UMqK8qo2hPz9MS9XxGZcKVefgM5WgCpIUHX/71pnz4L8FIoJSqcsb1QosZ7evIrr28ht0dTD9f7PQmpAtQcDXaAeSR/lk8ucp/0xV6rIX0ZQO0VLWmnaqdRHIPGeV5WzWw57GS7MvwGEQqP+98xchtpG3Cy/Grr3NFgfkiJz5035BqNNFb1YQecRQLXq47OzOohPMTQEmPYxAZ00KuZaWIoW/+Wclzui7iiMYR6+SdxxW2Swn0+ONJEc3dkzhpDiIdcTOmFLL0fHhm5TI5k7M5NFjx50Ez42GIM9gchDp+BXDpyKXPDvR06In3fLWsWLkRpyAkFdZJbuo6XVtxvE7Djk2BVuRj1SRuYz3fnwXQUmpTGx0/DTSqTEEJKIbvZgkHDkK1/sSIkmdgZEkXrzgAqaT96Znh9X1soeVL9tsOSZ3SyG6xRgYI7OtMI2f4u6YYGjaalP4hMKfZLyIri9kNkwSpqCw2NRfIRd0kNV87y9GxvFo+f9OuwwFRE16RQVn0RHtrrtn7bYzD5lbz/jTuCaglvt/JiGN2Rl7Mx01aRAPWcQhFNkp0blY+ebQ3tDHgkoxw8xNkX7P11HlzKGD3d8wI=
    # DOCKER_PASSWORD
    - secure: hCclD6JBRGxmBZ8VA2q3lKz76KUDEwTCr2xzZ7RZCEaebTzoSYIkDYE2uuB9HPT1YdI20tF2FowEJLRavrIVG52YS6cuEUh+63qX2b+OuFygtLUFSx+55xH9kMAVJNQ6JGsT6TPD0DTinuzp5ICa61fXLBUKXN1jH/fxyzsExz78viJNmAae6tzuVZyjN5P85Ojf8aIqQVXdHPW2qs3+rktLb3PL/+NYb78U61pBlZHbFWho5OXcZAudYMsvzuivHsGZKAKPWpxXomie7mQ5N8FeozTf3HYAomeo/wAHZf1w+S2DiFRQA2XT/Oz9/mAP37iCIFTB74QxXv5i6zPPw3bMdy6hIDiQl1x0vpJXepYJuT3noTybOQJucmR7jIICSWEoDWnEF4e3lqkk/RRkwCJM/G8shDItzoNQhfeNNO7Ao9MBet7cskNEh0ckMyjbksmghvP5bDL5hOZGhaJQn9AcF6CdYKhI4lbUjhm7IRm/EpapVBkk4RErs9GQB1fiOheEVuL3bABfWnbIGae9+WurLrmTXq3kBx7cWg2F8qtCF/tTx3RnoTibDndxwp5Gfu/SZq8WLcjo42BhcQTkRIhnYWB+O0B7DqW0i9kN3f8La3g1oAM/znym+HZMsIwTAfGATdYEND3iea5YOA71RkKarG5rHRk3zl1H+xL+/vc=

services:
  - docker

python:
  - '3.7'

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

script:
  - make -f Makefile-conda test
  - make docker-build
  - make docker-background-run
  - sleep 60
  - curl http://localhost:8888
  - make test
  - docker stop ganimede

deploy:
  provider: script
  script: make docker-push DOCKER_USERNAME=${DOCKER_USERNAME} DOCKER_PASSWORD=${DOCKER_PASSWORD}
  on:
    branch: master
