language: python

DOCKER_USERNAME:
  secure: kEr4zDUTPAigHh6KVw9uuH1NN48hCsglpz6ZGwYueOM1veyyJHGTuQP61NgCAdP/iACe7YV6gaPVSVInyoFGG5aE+2nESjINDWDPm3mY/WIiVne0aA4ngBpgAk2O7Tw8Q3PdcaZyZRi0ZFGLfj2bGMcvVM/pbBgQc3zkAAf5Dj4fHdjmtlNkpEuN9T//oFFSYukA04nNdhgwYj71tj/MqLXyqUY97gWf3dUPUnXZkcszgEik7Ju43wtjPArHRXQpiXxaxInGLN1ks0EmIOFwEeiNIv6nF/BPGIl1lfgGS84ybQCxNif4Pa33kPBD+EE71TAcB0c6bGCxB6OSvQMOnKA84dwdTyQuENyP4JTtQhERa9rgwgI5CPyEaBhxyzV+h4bPKEfhV9pBvSfWiJl9A4fblg4ZyT7CF/ugLV3bW57FJ7gkq+UOe+wIizDzoscuJHFXuCo6d4ZefSD+1AhUSlcVPVX/QiJTTg7mrvlTQisCiFX6Dt2xXkAbOmKX2gb1wJe/Y5/OLHNQwtKeVvTH7+WsMCSf6n4P6ms8yE0ePE8BYNRgmKya/eBBf/MW8fTstR+PAB/JDmzMaY0bbZaJttE2+XQzqU2K4neyioJYCO8Z8vsaSo80fGZ5fupIvRoFoDaqVN4cO8l2/sy9wUggC7tH9K9tfVhllatx1LgbnnE=
DOCKER_PASSWORD:
  secure: f76GvsamJk+k93g5xIalx+oySeR3jnKz2qiPGtg7j1P62Kv3U0Kvh8KRm6/kVSiIwCYQw9wWRmoYN2N3ZQ15YCmv+Uj8Ufbs/M2N1MKXlcBChOOR9cnT4MNlIzJp/c60IGjev/lRdYLk5q2u2pYe63+DAGKPZ4Uyj1J81AhZ+Rjg6jGOG3/lfzc59rvllYX8eCBgTAz+J4nlV7ZKvZSuHulYKItWJ53CJXbr03doS/iNTyoawoTQPKNlnGMnL6myEDMs5D4laHBVi//YP7IxXUQ2OsD4BkNIgfO8Z96/ROnP3TENZWo1eBJ4UEQGbrLIkJbEzPOoaHk2VmNFeK20C2ErzmESTIHF8R7L9D9555U6Lw7hG+XqAHeVzUVL2kMwnRvGsWbc8BEXLBkwC1s4LDkmNzzB0g2o+CJD6UffbAMgclu5aA/J33db3EdXYzFhv3RN2oQYIHSZx9eUTHStpXqcWnGWoIocbOb8/8rpcWLYVoKEtF2iF+ujJNiZpf08xf/tj6ygQ9CGLcjH+WM04RPFruWJ0Sq0KSt59zAt68u75KgSFCXhwdidKLx4B0JQBlOJU/aiynXpxuhnjSaOmkO1659JSedj4m628K/H5sc+bZ1ifCwXIKYVU6KK/vdaMkGQbSZ+hd4Nc0STiggdh/EL1peSxF8c76q+mKHHfq8=

services:
  - docker

python:
  - '3.7'

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

script:
  - make test
  - make docker-build

deploy:
  provider: script
  script: make docker-push DOCKER_USERNAME=${DOCKER_USERNAME} DOCKER_PASSWORD=${DOCKER_PASSWORD}
  on:
    branch: master
